config/routes.rb
TruthcommCom::Application.routes.draw do
  
  resources :quotes, :only => [:new, :create]
  match '/thankyou', :to => 'quotes#thankyou', :as => 'thankyou'

  get "comments/index"

  resources :comments
  namespace :admin do
    resources :comments
  end 

  match 'contact' => 'pages#contact'
  match 'carriers' => 'pages#carriers'
  match 'about' => 'pages#about'
  #match 'quote' => 'pages#quote'
  match 'services' => 'pages#services'
  match 'energy-services' => 'pages#energy', :as => 'energy'
  match 'phone-hardware' => 'pages#phone', :as => 'phone'
  match 'why-use-a-broker' => 'pages#broker', :as => 'broker'
  root :to => 'pages#index'

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  # Scopes
  named_scope :approved, :conditions => { :approved => true }
end

app/models/quote.rb
class Quote
  
  include ActiveModel::Validations

  validates_presence_of :name, :message
  
  validates_format_of :phone,
    :message => "must be a valid telephone number.",
    :with => /^[\(\)0-9\- \+\.]{10,20}$/
  
  validates_format_of :email,
    :message => 'email must be valid',
    :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/
                              

  attr_accessor :id, :name, :company_name, :email, :phone, :address, :phone_lines, :current_internet, :current_carrier, :message

  def initialize(attributes = {})
    attributes.each do |key, value|
      self.send("#{key}=", value)
    end
    @attributes = attributes
  end

  def read_attribute_for_validation(key)
    @attributes[key]
  end

  def to_key
  end

  def save
    if self.valid?
      QuoteMailer.quote_notification(self).deliver
      return true
    end
    return false
  end
  
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @comments }
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @comments = Comment.approved.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @comments }
    end
  end

  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @comment }
    end
  end

  def create
    @comment = Comment.new(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to(comments_path, :notice => 'Comment was successfully created.') }
        format.xml  { render :xml => @comment, :status => :created, :location => @comment }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to(admin_comments_path, :notice => 'Comment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to(admin_comments_path) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @title = "Welcome"
  end
  
  def services
    @title = "Services"
  end

  def quote
    @title = "Quote"
  end

  def about
    @title = "About"
  end
  
  def carriers
    @title = "Carriers"
  end
  
  def contact
    @title = "Contact Us"
  end
  
  def energy
    @title = "Energy Services"
  end
  
  def phone
    @title = "Phone Hardware"
  end
  
  def broker
    @title = "Why use a Broker?"
  end

end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController

  def new
    @quote = Quote.new(:id => 1)
    @title = "Request a quote"
  end

  def create
    @quote = Quote.new(params[:quote])
    if @quote.save
      redirect_to('/thankyou')
    else
      flash[:alert] = "You must fill out all fields."
      render 'new'
    end
  end
  
  def thankyou
    @title = "Thank you"
  end

end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/admin/comments/_form.html.haml
= form_for(@comment) do |f|
  - if @comment.errors.any?
    #error_explanation
      %h2
        = pluralize(@comment.errors.count, "error")
        prohibited this comment from being saved:
      %ul
        - @comment.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :author
    %br/
    = f.text_field :author
  .field
    = f.label :company_name
    %br/
    = f.text_field :company_name
  .field
    = f.label :title
    %br/
    = f.text_field :title
  .field
    = f.label :message
    %br/
    = f.text_area :message
  .field
    = f.label :approved
    %br/
    = f.check_box :approved
  .actions
    = f.submit

app/views/admin/comments/edit.html.haml
.inside
  %h1 Editing comment
  = render 'form'
  = link_to 'Show', comments_path, :target => '_blank'
  |
  =link_to 'Back', admin_comments_path

app/views/admin/comments/index.html.haml
.inside
  %h1 Listing comments
  %table
    %tr
      %th Message
      %th Author
      %th Approved
      %th
      %th
    - @comments.each do |comment|
      %tr
        %td= comment.message
        %td= comment.author
        %td= comment.approved
        %td= link_to 'Edit', edit_admin_comment_path(comment)
        %td= link_to 'Destroy', comment, :confirm => 'Are you sure?', :method => :delete

app/views/comments/_form.html.haml
= form_for(@comment) do |f|
  - if @comment.errors.any?
    #error_explanation
      %h2
        = pluralize(@comment.errors.count, "error")
        prohibited this comment from being saved:
      %ul
        - @comment.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :author
    %br/
    = f.text_field :author
  .field
    = f.label :company_name
    %br/
    = f.text_field :company_name
  .field
    = f.label :title
    %br/
    = f.text_field :title
  .field
    = f.label :message
    %br/
    = f.text_area :message
  .actions
    = f.submit

app/views/comments/index.html.haml
.inside
  #comments
    = image_tag('comments.jpg', :class => "picture_page")
    %br
    = link_to 'Add a Comment', new_comment_path, :id => 'link'
    %br
    %ul
      - @comments.each do |comment|
        %li
          %p= comment.message
          %strong= comment.author
          %br
          %span= comment.company_name
          %br
          %span= comment.title

app/views/comments/new.html.haml
.inside
  %h1 New comment
  = render 'form'

  = link_to 'Back', comments_path

app/views/layouts/application.html.haml
!!! 5
%html{ :lang => "en-US", "xml:lang" => "en-US", :xmlns => "http://www.w3.org/1999/xhtml" }
  %head
    %meta{ 'http-equiv' => "content-type", :content => "text/html; charset=utf-8" }
    %meta{ :name => "Author", :content => "Truthcomm" }
    %meta{ :name => "viewport", :content => "width=1024" }
    %title= 'Truthcomm - ' + @title ||= "Thanks for Visiting!"
    %meta{ :name => "Keywords", :content => "Truthcomm" }
    %meta{ :name => "Description", :content => "Truthcomm"}
    = stylesheet_link_tag 'screen.css', :media => 'screen, projection'
    = stylesheet_link_tag 'print.css', :media => 'print'
    /[if lt IE 8]
      = stylesheet_link_tag 'ie.css', :media => 'screen, projection'
    = javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js"
    = javascript_include_tag 'rails', 'application'
    %meta{:name => 'csrf-token', :content => form_authenticity_token}
    %meta{:name => 'csrf-param', :content => 'authenticity_token'}
  %body.bp
    #header
      #inside_header
        .logo
          = link_to image_tag('logo.png'), root_path
        .menu
          %ul
            %li= link_to "Home", root_path
            %li= link_to "Carriers", carriers_path
            %li= link_to "Phone Hardware", phone_path
            %li= link_to "Energy Services", energy_path
            %li= link_to "About", about_path            
            %li= link_to "Contact", contact_path
    #wrapper
      #container
        #content
          = yield
    #footerpusher
      #footer
        .copyright
          Copyright &copy; 2011 Truthcomm. All rights reserved.

app/views/pages/about.html.haml
.inside
  = image_tag('about.jpg', :class => "picture_page")
  %p
    Truth Communications was founded on the simple, but not so common principal that customers are the highest priority in any business.  We were tired of the traditional process involved in communication sales.  Often, we find customers whose needs were not met because of a lack of experience by the direct rep, or a complete disregard for the customer because the sales rep only represented one company and didn't want to lose the sale.
  %p
    We want to show customers the true cost of their telecom solutions.  The name Truth was driven from the idea that we can show customers the Truth about their bills, services and fees.  Quite often fees and surcharges are left off quotes, leaving decision makers in the dark and ultimately frustrated.  At Truth Communications full disclosure is the only policy.
  %p
    Our staff has over 31 combined years of experience working in the communications business.  Our experience includes high level management, sales, operations, and implementation.  Our cumulative experience gives us a competitive advantage, and allows us to give our customers the best overall service, support and pricing for their communication needs.
  %p
    Our customers can expect quick responses and resolutions.  We make sure that our customers are treated with the highest level of respect from both our staff and the carriers that we represent.  We look at every opportunity objectively and make sure that the Truth is revealed.

app/views/pages/broker.html.haml
.inside
  %h2 So what exactly is the difference between working with a broker versus working with a direct sales rep?  Let’s break it down…
  = image_tag('broker.jpg', :class => "picture_page")
  %strong Information
  %ul
    %li Direct Sales Rep:  Provides you with information on the specific company they work for. They only explore the options their company offers, ultimately limiting your options.
    %li Broker:  Supplies unbiased information regarding the various options available in the market from multiple carriers.  Brokers allow you to explore the positives and the negatives of each company, without having to meet with each one individually. You have the chance to see which carrier would best meet your business needs.
  %strong Relationship/Compensation
  %ul
    %li Direct Sales Rep:  Compensated by a one-time bonus for every new sale.  They are not penalized if you aren’t satisfied with the service you get.
    %li Broker:  Carriers pay brokers a small percentage of the monthly bill, for every month that the business pays.  It is important to the broker that you are satisfied with your service and continue to pay your bill, which is why you’ll get additional support that sales reps won’t provide.
  %strong Knowledge
  %ul
    %li Direct Sales Rep:  Provides you with information on one company. This limits your ability to compare what is available in your market.
    %li Broker:  Represents a variety of companies and has a clear understanding of what each carrier has to offer to a business.
  %strong Time
  %ul
    %li Direct Sales Rep:  Requires you to sit through multiple meetings with vendors, obtain pricing quotes and service comparisons on your own. While it sounds straight forward, the process can be very time consuming.
    %li Broker:  Understands that your time is valuable, so we spend the time meeting with carriers to fit your needs.  Instead of having multiple meetings with multiple vendors, we present the best possible solutions for you in one meeting.
  %strong Support
  %ul
    %li Direct Sales Rep:  Provides support through a customer care department.  Most of the time, this forces you to maneuver through any issues on your own.
    %li Broker:  Bridges the gap between customers and the service department of the carriers.  We get involved in the process of issue resolution, should a service problem occur.
  %strong Cost
  %ul
    %li Direct Sales Rep:  Can provide pricing information for their company only, forcing you to do your own comparisons.
    %li Broker:  Provides you with a comparison of multiple companies from a pricing perspective, al- lowing you to look at what company best meets your business needs.
  %strong Bottom Line
  %p Brokers exist to make your job as easy as possible…we know that you’re busy running your own business, and seldom have the time or energy to spend on this.  Typically the only reason people don’t work with a broker is simply because they’re unaware that a service like this exists.
  = link_to 'More info on why to use agents', 'pdf/10-reasons-to-use-agents.pdf'

app/views/pages/carriers.html.haml
.inside
  #client-logos
    .client
      .image
        = image_tag('icons/cbeyond.jpg')
      %p Cbeyond, Inc. (Cbeyond) provides managed communications and information technology (IT), services to its target market of small businesses in select large metropolitan areas across the United States. The Company’s services include local and long distance voice services, broadband Internet access, mobile voice and data, e-mail, voicemail, Web hosting, secure backup and file sharing, fax-to-e-mail, virtual private network, desktop security, hosted Microsoft Exchange, mobile workforce management, virtual receptionist, and other communications and IT services.
    .client
      .image
        = image_tag('icons/integra.jpg')
      %p Integra Telecom, Inc. ("Integra")* is a facilities-based, integrated communications carrier, offering products that fit the smallest businesses to fortune 500 hundred companies. Integra’s product offering includes local dial tone, domestic and international long distance, high-speed Internet and data services, voice messaging, and numerous ancillary services designed to support the communication needs of any business. Integra currently offers service in the western 11 states
    .client
      .image
        = image_tag('icons/XO.jpg')
      %p XO Communications brings leading national and local telecommunications services to businesses. Using their unique nationwide IP network, their extensive local metro networks and broadband wireless facilities, XO offers a variety of communications solutions, including local and long-distance voice; dedicated Internet access; industry leading VoIP bundles; Ethernet; and, MPLS IP-VPN services in 75 metropolitan markets across the U.S.
    .client
      .image
        = image_tag('icons/comcast.jpg')
      %p Comcast is a company that was founded in 1963 and now has situated themselves as the country's largest provider of cable services. They focus on bringing superior cable television, high speed internet and residential telephone service to customers throughout the United States.
    .client
      .image
        = image_tag('icons/qwest.jpg')
      %p Qwest Communications International Inc. (Qwest), is a provider of data, Internet, video and voice services. The Company operates its business in the 14-state region of Arizona, Colorado, Idaho, Iowa, Minnesota, Montana, Nebraska, New Mexico, North Dakota, Oregon, South Dakota, Utah, Washington and Wyoming. The Company’s products and services are provided using its telecommunications network, which consists of voice and data switches, copper cables, fiber optic broadband cables and other equipment. The majority of the Company’s network is located in its local service area. Within its local service area, Qwest’s network serves approximately 10.3 million access lines in 14 states and forms a portion of the public switched telephone network (PSTN).
    .client
      .image
        = image_tag('icons/firstcomm.png')
      %p First Communications is a leading integrated telecommunications carrier in the Midwestern United States. Founded in 1998, First Communications has built a highly scalable telecommunications platform, infrastructure and support system, which represents a combination of world-class technology, and cutting-edge product offerings. First Communications has over 214,000 customers and owns and operates network comprised of 4,500 route miles of fiber which offers industry leading low latency metro and long haul routes unique to most other carriers. First Communications is led by a strong management team that has operated telecom companies throughout all cycles of the telecommunications market.
    .client
      .image
        = image_tag('icons/accessone.png')
      %p As a privately held company, our mission is to offer our clients the finest, most reliable business communication services and support in the industry. Since 1993 we have continually strived to fulfill this mission and are proud to be one of the only service providers with an A+ rating from the Better Business Bureau®, Serving Chicago & Northern Illinois.
    .client
      .image
        = image_tag('icons/paetec.png')
      %p Today, PAETEC delivers personalized communications solutions and unmatched service to business-class customers in 86 of the nation's top 100 metropolitan areas. We are the premier alternative to the ILECs, based on our nationwide footprint, breadth of products, and quality of service. PAETEC's data and voice products - and our unique value-added offerings - help customers achieve cost-effective solutions.
    .client
      .image
        = image_tag('icons/ptgi.bmp')
      %p Like other industry leaders, Primus delivers high-quality solutions for more than 2.4 million consumers, including small & medium enterprises and multinational businesses. Unlike the rest, Primus takes advantage of global telecommunications deregulation. This allows Primus to bring you facilities-based networks and facilities-based datacenters for a sophisticated line of services to manage your complete E-Business and data communication needs. Primus has ownership interests in over 23 transoceanic fiber-optic cable systems in Europe, North and South America, and the Asia-Pacific region.
    .client
      .image
        = image_tag('icons/level3.png')
      %p Level 3 was founded on the premise that cost-effective, scalable and reliable networks were the future for the telecommunications business. Once called “the best funded start-up in history,” we continually invested in infrastructure to become a world-class communications provider and have won the trust of the world's most sophisticated communications companies. It’s been an interesting history and is an ongoing story, one that we think you’ll want to know about in greater detail.

app/views/pages/contact.html.haml
.inside
  = image_tag('contact_us.jpg', :class => "picture_page")
  .contact
    %p
      %strong Phone: 773-596-9910
      %br
      Fax: 773-326-0852 
    %p 
      %strong 2943 W Belmont Ave
      %br
      Chicago, IL 60618
    %p 
      Support: 
      = link_to "troubletracker@truthcomm.com", :mailto => "troubletracker@truthcomm.com"
      %br
      Email:
      = link_to "contact@truthcomm.com", :mailto => "contact@truthcomm.com"
  

app/views/pages/energy.html.haml
.inside
  = image_tag('energy_services.jpg', :class => "picture_page")
  %p
    %strong Energy services from a telecom broker?  Yes!  The two fields are actually very similar when you live in a deregulated state.
  %strong How it works:
  %p If you buy your energy directly from the distributor, they give you the default rates for that current time period and adjust the cost according to your usage.  In this environment, you are usually paying a much higher rate than is necessary.  Competitive energy companies can buy the energy for you at typically a lower cost.  They analyze your usage over your last 12 month period and calculate how much energy you actually need.  They can then go to the market and purchase what you need at a certain rate and provide that to the distributor.  What this means to you is your per kilowatt rate can be much lower, saving you money. 
  %p All energy companies are the same right?  Incorrect.  Some companies just sell you a low rate for your energy.  If you dig a little deeper though, you can find companies that not only lower your rate, but also look for ways to reduce the energy that you need.  There are programs that can actually earn you money to help reduce your cost!  This is good for your bottom line, and also helps the environment.  You can pat yourself on the back twice for being a hero to your company and saving the earth at the same time!
  %strong The process:
  %p Simply give us a copy of your current contract and last energy invoice, and we will do the rest for you.  The billing information is simply adjusted, making you a happy camper. And the best part is that there’s no installation process!
  

app/views/pages/index.html.haml
= image_tag('main.jpg')
#keymenu
  .container
    = image_tag('keymenu/broker.jpg')
    .content
      = link_to "Our Services", services_path
      %p 
        What we can offer
        %br
        to you.
  .container
    = image_tag('keymenu/phone.jpg')
    .content
      = link_to "Telecom Brokers", broker_path
      %p 
        Why use a broker vs.
        %br 
        a direct rep.
  .container
    = image_tag('keymenu/energy.jpg')
    .content
      = link_to "Request a Quote", new_quote_path
      %p
        Get a hassle free
        %br
        quote within 24 hours.
  .container
    = image_tag('keymenu/customer.jpg')
    .content
      = link_to "Customer Wall", comments_path
      %p See what our customer's comments are.
#keycontent
  .about
    %h2 Truthcomm
    %p It is the business of a telecom broker to help you explore what is available to meet your telecommunication and internet needs.  We want to assist you in looking at the offerings of a variety of carriers, so you can make a service and pricing decision that best fits the needs of your company.  
  .speed
    = image_tag('speedtest.png')
    .test
      %script{:src => "http://www.internetfrog.com/scripts/widgets/speedtest_widget.php", :type => "text/javascript"}
    

app/views/pages/phone.html.haml
.inside
  #client-logos
    .client
      .image
        = image_tag('icons/avaya.png')
      %p Avaya is a global leader in enterprise communications systems. The company provides Unified Communications, Contact Centers, Data solutions and related services directly and through its Channel partners to leading businesses and organizations around the world. Enterprises of all sizes depend on Avaya for state-of-the-art communications that improve efficiency, collaboration, customer service and competitiveness.
    .client
      .image
        = image_tag('icons/cisco.png')
      %p Cisco Systems, Inc. (NASDAQ: CSCO, NYSE: CSCO, SEHK: 4333) is an American-based multinational corporation that designs and sells consumer electronics, networking, voice, and communications technology and services. Headquartered in San Jose, California, Cisco has more than 70,714 employees and annual revenue of US$ 40.0 billion as of 2010. The stock was added to the Dow Jones Industrial Average on June 8, 2009, and is also included in the S&P 500 Index, the Russell 1000 Index, NASDAQ 100 Index and the Russell 1000 Growth Stock Index.[4] Cisco is one of the world's biggest technology corporations
    .client
      .image
        = image_tag('icons/asterisk.png')
      %p Asterisk is software that turns an ordinary computer into a communications server. Asterisk powers IP PBX systems, VoIP gateways, conference servers and more. It is used by small businesses, large businesses, call centers, carriers and governments worldwide. Asterisk is free and open source. Asterisk is sponsored by Digium
    .client
      .image
        = image_tag('icons/shoretel.png')
      %p ShoreTel's Unified Communications system encompasses phones, switches, & software designed for easy deployment and rapid flexibility by integrating voice, video, IM, & voicemail in one easy to use system with no single point of failure.
    .client
      .image
        = image_tag('icons/panasonic.png')
      %p Based in Secaucus, NJ, Panasonic System Networks Company of America is a unit of Panasonic Corporation of North America, the principal North American subsidiary of Panasonic Corporation (NYSE: PC). A comprehensive business-to-business solutions provider, the company develops and delivers reliable, affordable, and flexible solutions for communication, collaboration, security and productivity. The complete suite of solutions addresses home and business communications, security and surveillance systems, retail information systems, office productivity solutions, and high definition visual conferencing, keeping Panasonic customers connected, informed, accessible and secure.

app/views/pages/quote.html.haml
.inside
  %h1 Quote
  = image_tag('request_a_quote_page.jpg', :class => "picture_page")
  %p Just want the numbers? No Problem.  Please fill out the information below and in 24 Hours we will have the three best options put together for you in a spreadsheet and emailed over.  If we have any questions along the way we will reach out to you.  Please be as specific as possible.

app/views/pages/services.html.haml
.inside
  %h1 What you can expect from us…
  = image_tag('services.jpg', :class => "picture_page")
  %strong STEP 1:  Evaluation of current carrier
  %p The first item we address is measuring where you are with your current carrier.  You can provide us with the information, or we can find it for you.  We simply need the dates of the contract(s), amount of usage, number of lines, current bandwidth, and current pricing.
  %strong STEP 2:  Needs analysis
  %p After we figure out your current situation, then we learn more about what you are looking for.  If you already know exactly what you want, great!  If not, don’t worry.  We find a lot of people we talk to have an idea of what they want, but would still like our expertise and guidance.  After we evaluate your needs and wants, we’ll come up with plausible solutions that can be implemented.
  %strong STEP 3:  Shop around
  %p Carrier shopping then becomes the fun part for us!  Most organizations only look at a few different options…we look at them all.  The information we gathered from you will go out to all the carriers who are able to support your telecom needs.  We see who comes back with the best overall fit, at the best overall cost, and compile the information into a simple and easy-to-read document.  Based on our experience and your specific telecom needs, we will detail the pros and the cons for each carrier, as well as any other relevant information you’ll need to weigh your options.  Furthermore, all the fees are disclosed up front so you know what the bottom line will be.  You will be able to make a confident decision knowing you did your due diligence.
  %strong STEP 4:  Implementation and installation
  %p Done!  Of course not…you might be done, but our work is just getting started.  We kick into high gear, coordinating and communicating with vendors to make sure the plan is smoothly executed.  We make sure all of the little details are handled so you don’t have to worry, or take time away from your business.  We do everything we can to make sure the installation process happens so efficiently that it won’t disrupt your work.  Your responsibility is simply to open the doors for the technicians!
  %strong STEP 5: Follow Up
  %p After all the pieces are in place, we take one last step to ensure your satisfaction.  We do a first bill review with you to make sure your expectations were met.  If they were not, then we’ll take the appropriate steps to fix them.  We will continue to be your support team to handle any telecom questions or issues that may come up.
  %p
    %stong The best part of our service is that it is free!
    Yes, we said free.  Our services are paid for by the carriers that we place the services through.  So, how do we get paid?  The carrier simply pays us a monthly percentage of your bill.  Now, you’re probably thinking “Does that mean that we’ll end up paying more?”  And the answer is, No!  Carriers factor in a monthly fee for marketing their product, whether that’s through a direct rep who works for that particular company, or a third party vendor such as TruthComm.  If you’re curious to learn more about how we get paid by saving you money, simply give us a call!  We provide full disclosure.

  %h2 Services include:
  %ul  
    %li Bill Review
    %li Billing Corrections/Credits
    %li Carrier Shopping
    %li Equipment Survey 
    %li Implementation Management
    %li Troubleshooting
    %li Customer Service

app/views/quotes/_form.html.haml
= form_for @quote, :url => { :action => "create" }, :html => { :method => :post } do |f|
  - if @quote.errors.any?
    #error_explanation
      %h2
        = pluralize(@quote.errors.count, "error")
        prohibited this quote from being saved:
      %ul
        - @quote.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :company_name
    %br/
    = f.text_field :company_name
  .field
    = f.label :phone
    %br/
    = f.text_field :phone
  .field
    = f.label :email
    %br/
    = f.text_field :email
  .field
    = f.label :address
    %br/
    = f.text_field :address
  .field
    = f.label :phone_lines
    %br/
    = f.select :phone_lines, options_for_select(["1", "2", "3", "4", "5", "6", "7", "8", "9", "10+"])
  .field
    = f.label :current_internet
    %br/
    = f.text_field :current_internet
  .field
    = f.label :current_carrier
    %br/
    = f.text_field :current_carrier
  .field
    = f.label :message
    %br/
    = f.text_area :message
  .actions
    = f.submit "Submit"

app/views/quotes/new.html.haml
.inside
  %h1 Quote
  = image_tag('request_a_quote_page.jpg', :class => "picture_page")
  %p Just want the numbers? No Problem.  Please fill out the information below and in 24 Hours we will have the three best options put together for you in a spreadsheet and emailed over.  If we have any questions along the way we will reach out to you.  Please be as specific as possible.

  = render 'form'

app/views/quotes/thankyou.html.haml
.inside
  %h1 Thank you!
  %p We have received your message and want to thank you. Your communication is important to us.

  %p Someone will review your message and contact you shortly.

  %p Thanks again for your interest in Truthcomm.com.

  %strong Sincerely,

  %p Truthcomm.com